services:
  #asp .net web application
  webapp:
    container_name: benefit-seller-api
    build:
      context: ./BenefitSeller.API
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000;https://0.0.0.0:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Partizan1998@
      - Database__ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=benefitseller;Username=postgres;Password=strong_password;
    networks:
      - postgres
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - C:/Users/seker/.aspnet/https:/https:ro
  # mssql database
  db:
    container_name: benefit-seller-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: benefitseller
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strong_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d benefitseller"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres
  pgadmin:
    container_name: pg-admin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: sekerusratko@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgAdminPassword
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped
volumes:
  postgres_data:
  pgadmin:

networks:
  postgres:
